name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  typecheck:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Type Check
    - run: yarn
    - run: yarn typecheck

  test: 
    runs-on: [ubuntu-latest, macos-latest]
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build & Test
      - run: yarn
      - run: yarn build
      - run: yarn test
